# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Generate a SYNTHETIC test library for the S1 Bridge spike (no real audio, ever).

Every track is a linear chirp generated by ``ffmpeg -f lavfi aevalsrc``:
    f(t) = F0 + K * t   (F0 = 200 Hz, K = 5 Hz/s, i.e. 200 Hz at 0 s, 2 kHz at 6 min)
so ffmpeg_bench.py can recover the real position of a clip from its pitch and measure
the seek error (-ss before -i), notably on MP3 VBR and M4A with moov at the end.

Usage:
    uv run spikes/bridge/fixtures.py [--out DIR] [--ffmpeg PATH] [--quick] [--force]

Default output: spikes/bridge/_fixtures/library/ (gitignored) and a manifest
spikes/bridge/_fixtures/manifest.json (outside the library root) describing the expected
outcome of each file.
"""

from __future__ import annotations

import argparse
import json
import os
import random
import subprocess
import sys
import time
import unicodedata

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import bridge_common as bc  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT_OUT = os.path.join(HERE, "_fixtures", "library")

CHIRP_F0 = 200.0
CHIRP_K = 5.0
SOURCE_RATE = 44100

# name -> (extension, muxer, codec args)
FORMATS: dict[str, tuple[str, str, list[str]]] = {
    "flac": (".flac", "flac", ["-c:a", "flac"]),
    "mp3-cbr192": (".mp3", "mp3", ["-c:a", "libmp3lame", "-b:a", "192k", "-id3v2_version", "3"]),
    "mp3-vbr-q2": (".mp3", "mp3", ["-c:a", "libmp3lame", "-q:a", "2", "-id3v2_version", "3"]),
    "m4a-aac-moov-end": (".m4a", "ipod", ["-c:a", "aac", "-b:a", "192k"]),  # no +faststart
    "wav": (".wav", "wav", ["-c:a", "pcm_s16le"]),
    "ogg-vorbis": (".ogg", "ogg", ["-c:a", "libvorbis", "-q:a", "5"]),
    "opus": (".opus", "opus", ["-c:a", "libopus", "-b:a", "128k", "-ar", "48000"]),
    "aiff": (".aiff", "aiff", ["-c:a", "pcm_s16be", "-write_id3v2", "1"]),
}
EXTRA_FORMATS: dict[str, tuple[str, str, list[str]]] = {
    "aac-adts": (".aac", "adts", ["-c:a", "aac", "-b:a", "160k"]),  # duration only estimated
    "oga-flac": (".oga", "oga", ["-c:a", "flac"]),
    "wma": (".wma", "asf", ["-c:a", "wmav2", "-b:a", "128k"]),
}
# VBR MP3 WITHOUT Xing/VBRI header (old rips): ffprobe estimates the duration from the first
# frame's bitrate. With a quiet start (lowest-bitrate frames) the estimate is far too long and
# the §10 start point can land after the real end. Generated only by the dedicated case below.
NOXING_FORMAT = ("mp3-vbr-noxing", (".mp3", "mp3", ["-c:a", "libmp3lame", "-q:a", "0",
                                                     "-write_xing", "0", "-id3v2_version", "3"]))
DURATIONS = [5, 45, 180, 360]
QUICK_DURATIONS = [5, 45, 180]


def chirp_source(duration: float, lead_silence: float = 0.0) -> list[str]:
    expr = f"0.5*sin(2*PI*({CHIRP_F0}*t+{CHIRP_K / 2}*t*t))"
    if lead_silence:
        # Silent until lead_silence, then the same chirp (phase still follows absolute t, so the
        # pitch keeps giving the position). (1+sgn(x))/2 is a step without commas (filtergraph).
        expr += f"*(1+sgn(t-{lead_silence}))/2"
    return ["-f", "lavfi", "-i", f"aevalsrc=exprs={expr}:s={SOURCE_RATE}:d={duration}"]


class Builder:
    def __init__(self, ffmpeg: str, root: str) -> None:
        self.ffmpeg = ffmpeg
        self.root = root
        self.manifest: list[dict] = []
        self.counter = 0

    def path(self, relpath: str) -> str:
        full = os.path.join(self.root, *relpath.split("/"))
        os.makedirs(os.path.dirname(full), exist_ok=True)
        return full

    def run(self, argv: list[str]) -> None:
        proc = subprocess.run(argv, capture_output=True, stdin=subprocess.DEVNULL)
        if proc.returncode != 0:
            raise SystemExit("ffmpeg failed:\n" + proc.stderr.decode("utf-8", "replace")[-2000:])

    def track(self, relpath: str, fmt: str, duration: float, *, cover: str | None = None,
              expected: str | None = None, note: str = "", lead_silence: float = 0.0,
              start_fraction: float | None = None) -> str:
        ext, muxer, codec = {**FORMATS, **EXTRA_FORMATS, NOXING_FORMAT[0]: NOXING_FORMAT[1]}[fmt]
        self.counter += 1
        title = f"Synthetic Track {self.counter}"
        out = self.path(relpath)
        argv = [self.ffmpeg, "-nostdin", "-hide_banner", "-loglevel", "error", "-y",
                *chirp_source(duration, lead_silence)]
        if cover:
            argv += ["-i", cover, "-map", "0:a", "-map", "1:v", "-c:v", "mjpeg",
                     "-disposition:v", "attached_pic"]
        argv += ["-ac", "2", *codec,
                 "-metadata", f"title={title}", "-metadata", "artist=OpenBlindySir Synth",
                 "-metadata", "album=Spike S1 Fixtures", "-f", muxer, out]
        self.run(argv)
        if expected is None:
            expected = "TOO_SHORT" if duration < bc.TOO_SHORT_S else "OK"
        entry = {
            "fs_relpath": relpath, "format": fmt, "duration": duration, "title": title,
            "has_cover": bool(cover), "expected": expected, "chirp": True, "note": note,
        }
        if lead_silence:
            entry["lead_silence"] = lead_silence
        if start_fraction is not None:
            entry["start_fraction"] = start_fraction  # ffmpeg_bench uses it instead of a random one
        if fmt.startswith("m4a"):
            entry["moov"] = bc.moov_position(out)
        self.manifest.append(entry)
        return out

    def raw(self, relpath: str, data: bytes, expected: str, note: str = "") -> str:
        out = self.path(relpath)
        with open(out, "wb") as fh:
            fh.write(data)
        self.manifest.append({"fs_relpath": relpath, "format": "raw", "expected": expected,
                              "chirp": False, "note": note})
        return out


def set_windows_attr(path: str, attr: int) -> bool:
    if not bc.IS_WINDOWS:
        return False
    import ctypes

    current = ctypes.windll.kernel32.GetFileAttributesW(path)
    return bool(ctypes.windll.kernel32.SetFileAttributesW(path, current | attr))


def clear_windows_attrs(root: str) -> None:
    """Hidden/system attributes would block a plain rmtree-free regeneration; clear them."""
    if not bc.IS_WINDOWS or not os.path.isdir(root):
        return
    import ctypes

    for dirpath, dirnames, filenames in os.walk(root):
        for name in filenames + dirnames:
            ctypes.windll.kernel32.SetFileAttributesW(os.path.join(dirpath, name), 0x80)


def main() -> int:
    bc.setup_console()
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=DEFAULT_OUT, help="library root to create")
    ap.add_argument("--manifest", default=None, help="manifest path (default: <out>/../manifest.json)")
    ap.add_argument("--ffmpeg", default=None)
    ap.add_argument("--quick", action="store_true", help="skip the 6 min tracks")
    ap.add_argument("--force", action="store_true", help="delete an existing output folder first")
    ap.add_argument("--seed", type=int, default=1234)
    args = ap.parse_args()

    ffmpeg = bc.find_tool("ffmpeg", args.ffmpeg, "OPENBLINDYSIR_FFMPEG")
    root = os.path.abspath(args.out)
    manifest_path = args.manifest or os.path.join(os.path.dirname(root), "manifest.json")
    if os.path.exists(root):
        if not args.force:
            raise SystemExit(f"{root} exists; use --force to regenerate")
        clear_windows_attrs(root)
        bc.safe_rmtree(root)
    os.makedirs(root)
    t0 = time.perf_counter()
    b = Builder(ffmpeg, root)
    rng = random.Random(args.seed)

    # Cover image (also a non-audio file in the library).
    cover = b.path("Edge/cover.jpg")
    b.run([ffmpeg, "-nostdin", "-hide_banner", "-loglevel", "error", "-y", "-f", "lavfi",
           "-i", "color=c=0x3366cc:s=320x320:d=1", "-frames:v", "1", cover])
    b.manifest.append({"fs_relpath": "Edge/cover.jpg", "format": "raw", "expected": "SKIPPED_EXT",
                       "chirp": False, "note": "non-audio"})

    # 1. Format x duration matrix.
    durations = QUICK_DURATIONS if args.quick else DURATIONS
    for fmt, (ext, _muxer, _codec) in FORMATS.items():
        for d in durations:
            b.track(f"Formats/{fmt}/track-{d:03d}s{ext}", fmt, d)
    for fmt, (ext, _muxer, _codec) in EXTRA_FORMATS.items():
        b.track(f"Formats/extra/{fmt}-045s{ext}", fmt, 45)

    # 2. Cover art (attached picture) on one MP3 and one FLAC: -map 0:a:0 must drop it.
    b.track("Edge/with cover art.mp3", "mp3-cbr192", 180, cover=cover, note="attached picture")
    b.track("Edge/with cover art.flac", "flac", 180, cover=cover, note="attached picture")

    # 3. Unicode names: NFC and NFD folders/files, plus a deliberate NFC collision.
    nfc_cafe = unicodedata.normalize("NFC", "Café")
    nfd_cafe = unicodedata.normalize("NFD", "Café")
    assert nfc_cafe != nfd_cafe
    b.track(f"Unicode/{nfc_cafe}/nfc-only.mp3", "mp3-vbr-q2", 45)
    b.track(f"Unicode/{nfd_cafe}/nfd-only.mp3", "mp3-vbr-q2", 45, note="NFD folder")
    b.track(f"Unicode/{nfc_cafe}/collision.ogg", "ogg-vorbis", 45, note="NFC twin")
    b.track(f"Unicode/{nfd_cafe}/collision.ogg", "ogg-vorbis", 45,
            expected="COLLISION", note="NFD twin: same NFC relpath as the NFC one")
    b.track("Unicode/アニメ/オープニング.flac", "flac", 180)
    b.track(unicodedata.normalize("NFD", "Unicode/Beyoncé - Déjà vu.m4a"), "m4a-aac-moov-end",
            180, note="NFD file name")
    b.track("Unicode/🎵 Emoji/track.opus", "opus", 45)

    # 4. Edge cases.
    b.track("Edge/-dash-start.mp3", "mp3-cbr192", 45, note="name starts with '-'")
    b.track("Edge/UPPER.MP3", "mp3-cbr192", 45, note="upper-case extension")
    b.track("Edge/very short 3s.wav", "wav", 3, expected="TOO_SHORT")
    b.track("Edge/40s one-third rule.flac", "flac", 40, note="empty window, 1/3 start shortens clip")
    b.track("Edge/12s whole track.flac", "flac", 12, note="shorter than clip: whole track")
    b.track("Edge/.hidden.mp3", "mp3-cbr192", 45, expected="SKIPPED_HIDDEN")
    b.track("Edge/.hidden-dir/inside.mp3", "mp3-cbr192", 45, expected="SKIPPED_HIDDEN")
    hidden = b.track("Edge/hidden-attr.mp3", "mp3-cbr192", 45, expected="SKIPPED_HIDDEN")
    system = b.track("Edge/system-attr.mp3", "mp3-cbr192", 45, expected="SKIPPED_HIDDEN")
    if bc.IS_WINDOWS:
        set_windows_attr(hidden, bc.FILE_ATTRIBUTE_HIDDEN)
        set_windows_attr(system, bc.FILE_ATTRIBUTE_SYSTEM)
    else:
        for entry in b.manifest[-2:]:
            entry["expected"] = "OK"
            entry["note"] = "attribute not settable on this OS"
        b.track("Edge/colon:name.mp3", "mp3-cbr192", 45, note="':' in name (POSIX only)")
    b.raw("Edge/notes.txt", b"Synthetic fixture library for the OpenBlindySir S1 spike.\n",
          "SKIPPED_EXT", "non-audio")
    b.raw("Edge/empty.flac", b"", "DECODE_ERROR", "empty file")
    b.raw("Edge/corrupt.mp3", rng.randbytes(65536), "DECODE_ERROR", "random bytes")
    truncated = b.track("Edge/truncated.flac", "flac", 180, start_fraction=0.29,
                        note="cut at 40 %: header says 180 s; at fraction 0.29 the source ends "
                             "~27 s after the start: the output check re-encodes with the real "
                             "length so the fade-out is kept (OK, reencoded)")
    with open(truncated, "r+b") as fh:
        fh.truncate(int(os.path.getsize(truncated) * 0.4))
    b.track("Deep/a/b/c/d/e/f/g/h/deep.mp3", "mp3-vbr-q2", 180)
    # VBR MP3 without Xing header, 30 s of silence then the chirp: ffprobe overestimates the
    # duration ("Estimating duration from bitrate"). Late fixed start fraction (0.95): with the
    # plain §10 rule the start lands after the real end (empty clip -> DECODE_ERROR); with the
    # spike's duration measure it is OK.
    b.track("Edge/vbr-noxing-quiet-start.mp3", NOXING_FORMAT[0], 180, lead_silence=30.0,
            start_fraction=0.95, note="VBR MP3 without Xing/VBRI, quiet start: estimated duration")

    os.makedirs(os.path.dirname(manifest_path), exist_ok=True)
    with open(manifest_path, "w", encoding="utf-8") as fh:
        json.dump({"root": root, "chirp": {"f0": CHIRP_F0, "k": CHIRP_K},
                   "files": b.manifest}, fh, ensure_ascii=False, indent=1)

    total = sum(os.path.getsize(os.path.join(dp, f)) for dp, _d, fs in os.walk(root) for f in fs)
    moov = [e["moov"] for e in b.manifest if "moov" in e]
    print(f"fixtures: {len(b.manifest)} files, {bc.human_bytes(total)}, "
          f"{time.perf_counter() - t0:.1f} s")
    print(f"m4a moov positions (expected all 'end'): {sorted(set(moov))} over {len(moov)} files")
    print(f"library : {root}")
    print(f"manifest: {manifest_path}")
    return 0 if set(moov) == {"end"} else 1


if __name__ == "__main__":
    sys.exit(main())
