// AUTO-GENERATED by tools/gen_ts_types.py — DO NOT EDIT.

export const PROTOCOL_VERSION = 10;

export const ANSWER_HARD_MAX = 1500;

export const NICKNAME_MAX = 24;

export const POINTS_BOUND = 1000;

export const WS_PLAYER_MAX_BYTES = 16384;

export const CloseCode = { SUPERSEDED: 4001, KICKED: 4003, SESSION_ENDED: 4004 } as const;

export type AnswerAckStatus = "accepted" | "rejected";
export const ANSWER_ACK_STATUSES = ["accepted", "rejected"] as const;

export type AnswerRejectReason = "closed" | "not_open" | "wrong_round" | "already_locked" | "not_participant" | "empty" | "too_long";
export const ANSWER_REJECT_REASONS = ["closed", "not_open", "wrong_round", "already_locked", "not_participant", "empty", "too_long"] as const;

export type AnswerStatus = "NONE" | "DRAFT" | "LOCKED" | "CAPTURED";
export const ANSWER_STATUSES = ["NONE", "DRAFT", "LOCKED", "CAPTURED"] as const;

export type AssetFailureCode = "NO_AUDIO" | "silent_audio" | "NOT_FOUND" | "DECODE_ERROR" | "TOO_SHORT" | "TIMEOUT" | "BRIDGE_OFFLINE" | "INVALID_UPLOAD" | "CANCELLED";
export const ASSET_FAILURE_CODES = ["NO_AUDIO", "silent_audio", "NOT_FOUND", "DECODE_ERROR", "TOO_SHORT", "TIMEOUT", "BRIDGE_OFFLINE", "INVALID_UPLOAD", "CANCELLED"] as const;

export type AssetRole = "previous" | "current" | "next" | "next2";
export const ASSET_ROLES = ["previous", "current", "next", "next2"] as const;

export type AssetState = "REQUESTED" | "ENCODING" | "UPLOADING" | "STORED" | "EVICTED" | "FAILED";
export const ASSET_STATES = ["REQUESTED", "ENCODING", "UPLOADING", "STORED", "EVICTED", "FAILED"] as const;

export type AudioErrorCode = "FETCH_FAILED" | "DECODE_FAILED" | "CONTEXT_FAILED";
export const AUDIO_ERROR_CODES = ["FETCH_FAILED", "DECODE_FAILED", "CONTEXT_FAILED"] as const;

export type AudioState = "LOCKED" | "IDLE" | "LOADING" | "READY" | "PLAYING" | "ERROR";
export const AUDIO_STATES = ["LOCKED", "IDLE", "LOADING", "READY", "PLAYING", "ERROR"] as const;

export type BridgeState = "OFFLINE" | "CONNECTED" | "SYNCING" | "ONLINE" | "REJECTED";
export const BRIDGE_STATES = ["OFFLINE", "CONNECTED", "SYNCING", "ONLINE", "REJECTED"] as const;

export type BrowserFamily = "chromium" | "firefox" | "safari" | "ios_webkit" | "other";
export const BROWSER_FAMILYS = ["chromium", "firefox", "safari", "ios_webkit", "other"] as const;

export type CancelReason = "skipped" | "end_game" | "undo_discarded";
export const CANCEL_REASONS = ["skipped", "end_game", "undo_discarded"] as const;

export type ClipFormat = "aac" | "opus";
export const CLIP_FORMATS = ["aac", "opus"] as const;

export type CloseReason = "deadline" | "all_locked" | "host" | "end_game";
export const CLOSE_REASONS = ["deadline", "all_locked", "host", "end_game"] as const;

export type ConnectionState = "ONLINE" | "OFFLINE" | "REMOVED";
export const CONNECTION_STATES = ["ONLINE", "OFFLINE", "REMOVED"] as const;

export type EndGameMode = "score" | "abandon";
export const END_GAME_MODES = ["score", "abandon"] as const;

export type ErrorCode = "invalid_message" | "hello_required" | "protocol_mismatch" | "not_host" | "invalid_state" | "stale_command" | "unknown_player" | "invalid_args" | "no_sources" | "bridge_offline" | "no_competitors" | "pool_exhausted" | "unreviewed_scores" | "scores_frozen" | "rate_limited" | "message_too_large" | "bad_password" | "nickname_invalid" | "nickname_taken" | "game_full" | "already_joined" | "unauthenticated" | "forbidden_origin" | "json_required" | "not_found" | "payload_too_large" | "upload_rejected" | "join_locked" | "recovery_invalid" | "review_unavailable";
export const ERROR_CODES = ["invalid_message", "hello_required", "protocol_mismatch", "not_host", "invalid_state", "stale_command", "unknown_player", "invalid_args", "no_sources", "bridge_offline", "no_competitors", "pool_exhausted", "unreviewed_scores", "scores_frozen", "rate_limited", "message_too_large", "bad_password", "nickname_invalid", "nickname_taken", "game_full", "already_joined", "unauthenticated", "forbidden_origin", "json_required", "not_found", "payload_too_large", "upload_rejected", "join_locked", "recovery_invalid", "review_unavailable"] as const;

export type GamePhase = "LOBBY" | "IN_GAME" | "FINAL_SCORE_REVIEW" | "FINAL_RESULTS";
export const GAME_PHASES = ["LOBBY", "IN_GAME", "FINAL_SCORE_REVIEW", "FINAL_RESULTS"] as const;

export type HostMode = "player" | "mc";
export const HOST_MODES = ["player", "mc"] as const;

export type HostWarning = "bridge_offline" | "pool_exhausted" | "cache_full" | "track_replaced" | "round_failed";
export const HOST_WARNINGS = ["bridge_offline", "pool_exhausted", "cache_full", "track_replaced", "round_failed"] as const;

export type JobFailureCode = "NO_AUDIO" | "silent_audio" | "NOT_FOUND" | "DECODE_ERROR" | "TOO_SHORT" | "TIMEOUT" | "INVALID_UPLOAD" | "CANCELLED" | "QUEUE_FULL";
export const JOB_FAILURE_CODES = ["NO_AUDIO", "silent_audio", "NOT_FOUND", "DECODE_ERROR", "TOO_SHORT", "TIMEOUT", "INVALID_UPLOAD", "CANCELLED", "QUEUE_FULL"] as const;

export type JobStage = "probing" | "encoding" | "uploading";
export const JOB_STAGES = ["probing", "encoding", "uploading"] as const;

export type Role = "player" | "host";
export const ROLES = ["player", "host"] as const;

export type RoundState = "QUEUED" | "PREPARING" | "LOADING" | "COUNTDOWN" | "OPEN" | "REVIEW" | "REVEALED" | "FAILED" | "CANCELLED";
export const ROUND_STATES = ["QUEUED", "PREPARING", "LOADING", "COUNTDOWN", "OPEN", "REVIEW", "REVEALED", "FAILED", "CANCELLED"] as const;

export type ScoreKind = "round" | "adjustment" | "final_adjustment" | "revoke";
export const SCORE_KINDS = ["round", "adjustment", "final_adjustment", "revoke"] as const;

export type StartBlocker = "no_sources" | "bridge_offline" | "no_competitors" | "pool_exhausted";
export const START_BLOCKERS = ["no_sources", "bridge_offline", "no_competitors", "pool_exhausted"] as const;

export interface AddTimeArgs {
  readonly expected_deadline: number;
}

export interface AdjustArgs {
  readonly player_id: string;
  readonly delta: number;
  readonly round_id?: string | null;
  readonly note?: string | null;
  readonly op_id: string;
}

export interface AdjustmentEntry {
  readonly kind: string;
  readonly delta: number;
  readonly round_number: number | null;
  readonly note: string | null;
}

export interface AnswerAck {
  readonly t: "ANSWER_ACK";
  readonly round_id: string;
  readonly status: AnswerAckStatus;
  readonly reason: AnswerRejectReason | null;
}

export interface AnswerDraft {
  readonly t: "ANSWER_DRAFT";
  readonly round_id: string;
  readonly text: string;
}

export interface AnswerSubmit {
  readonly t: "ANSWER_SUBMIT";
  readonly round_id: string;
  readonly text: string;
}

export interface ArchiveSource {
  readonly bridge_id: string;
  readonly name: string;
}

export interface AudioRef {
  readonly asset_id: string;
  readonly url: string;
  readonly duration_ms: number;
}

export interface AudioSlots {
  readonly current: AudioRef | null;
  readonly next: AudioRef | null;
}

export interface AudioStatus {
  readonly t: "AUDIO_STATUS";
  readonly state: AudioState;
  readonly asset_id?: string | null;
  readonly error?: AudioErrorCode | null;
  readonly clock: ClockInfo;
}

export interface AutoMatchInfo {
  readonly criterion: string;
  readonly reference: string | null;
  readonly fragment: string | null;
  readonly similarity: number;
  readonly threshold: number;
  readonly status: string;
}

export interface BridgeDetail {
  readonly bridge_id: string;
  readonly name: string;
  readonly version: string;
  readonly protocol: number;
  readonly state: BridgeState;
  readonly track_count: number;
  readonly jobs_in_flight: number;
  readonly formats: readonly string[];
  readonly allow_full_review: boolean;
  readonly source_error: string | null;
}

export interface BridgeStatus {
  readonly state: BridgeState;
  readonly name: string | null;
  readonly track_count: number;
  readonly jobs_in_flight: number;
}

export interface ClockInfo {
  readonly offset: number | null;
  readonly rtt_min: number | null;
}

export interface Compatibility {
  readonly server_version: string;
  readonly protocol: number;
  readonly protocol_min: number;
  readonly protocol_max: number;
  readonly snapshot_format: number;
  readonly history_format: number;
}

export interface ConfirmRequest {
  readonly confirm: boolean;
}

export interface DiagCacheAsset {
  readonly asset_ref: string;
  readonly role: AssetRole | null;
  readonly state: AssetState;
  readonly bytes: number;
}

export interface DiagJob {
  readonly job_id: string;
  readonly asset_state: AssetState;
  readonly stage: JobStage | null;
  readonly age_ms: number;
  readonly bridge_id: string | null;
}

export interface DiagPlayer {
  readonly player_id: string;
  readonly nickname: string;
  readonly connection: ConnectionState;
  readonly audio_state: AudioState;
  readonly audio_error: AudioErrorCode | null;
  readonly rtt_min_ms: number | null;
  readonly offset_ms: number | null;
  readonly epsilon_ms: number | null;
  readonly last_late_ms: number | null;
  readonly last_est_error_ms: number | null;
  readonly out_latency_ms: number | null;
  readonly client_version: string | null;
  readonly browser_family: BrowserFamily | null;
}

export interface DiagRound {
  readonly round_id: string;
  readonly number: number;
  readonly state: RoundState;
  readonly unvalidated: readonly DiagUnvalidated[];
  readonly playback_p50_ms: number | null;
  readonly playback_p90_ms: number | null;
  readonly playback_max_ms: number | null;
}

export interface DiagUnvalidated {
  readonly player_id: string;
  readonly draft_last_changed_ms: number | null;
}

export interface DiagnosticsResponse {
  readonly server_version: string;
  readonly protocol: number;
  readonly uptime_s: number;
  readonly loop_lag_p99_ms: number;
  readonly players: readonly DiagPlayer[];
  readonly bridge: BridgeStatus;
  readonly jobs: readonly DiagJob[];
  readonly cache_used_bytes: number;
  readonly cache_cap_bytes: number;
  readonly cache: readonly DiagCacheAsset[];
  readonly rounds: readonly DiagRound[];
  readonly compatibility: Compatibility | null;
  readonly bridges: readonly BridgeDetail[];
  readonly persistence_status: string;
  readonly history_count: number;
  readonly history_bytes: number;
}

export type EmptyArgs = Readonly<Record<string, never>>;

export interface EndGameArgs {
  readonly current_round: EndGameMode;
}

export interface ErrorMsg {
  readonly t: "ERROR";
  readonly code: ErrorCode;
  readonly compatibility: Compatibility | null;
}

export interface ErrorResponse {
  readonly error: ErrorCode;
}

export interface FinalAdjustmentShown {
  readonly note: string | null;
  readonly player_id: string;
  readonly delta: number;
}

export interface FinalResults {
  readonly standings: readonly StandingRow[];
  readonly podium: readonly StandingRow[];
  readonly rounds_played: number;
  readonly final_adjustments: readonly FinalAdjustmentShown[];
  readonly recap: readonly FinalReviewRow[];
  readonly finished_at: number | null;
  readonly podium_started_at: number | null;
}

export interface FinalReviewRow {
  readonly draft_note: string | null;
  readonly player_id: string;
  readonly score_before: number;
  readonly draft_delta: number;
  readonly score_after: number;
  readonly history: readonly HistoryEntry[];
  readonly adjustments: readonly AdjustmentEntry[];
}

export interface FinalSetArgs {
  readonly player_id: string;
  readonly delta: number;
  readonly note?: string | null;
  readonly expected_delta?: number | null;
  readonly expected_note?: string | null;
}

export interface Finale {
  readonly round: FinaleRound | null;
  readonly revealed_round_ids: readonly string[];
  readonly rounds_total: number;
  readonly reviewed: number;
  readonly expected: number;
  readonly standings: readonly StandingRow[];
  readonly teams: readonly TeamStanding[];
}

export interface FinaleAnswer {
  readonly player_id: string;
  readonly text: string | null;
  readonly points: number;
  readonly reviewed: boolean;
  readonly revision: number;
  readonly title_correct: boolean | null;
  readonly artist_correct: boolean | null;
  readonly custom_correct: boolean | null;
  readonly album_correct: boolean | null;
  readonly year_correct: boolean | null;
  readonly featuring_correct: boolean | null;
}

export interface FinaleRevealArgs {
  readonly round_id: string;
  readonly fast_forward?: boolean;
}

export interface FinaleRound {
  readonly awards_pending: boolean;
  readonly round_id: string;
  readonly number: number;
  readonly track: RevealTrack | null;
  readonly answers: readonly FinaleAnswer[];
  readonly included: boolean;
}

export interface FolderNode {
  readonly name: string;
  readonly prefix: string;
  readonly track_count: number;
  readonly children: readonly FolderNode[];
  readonly fresh_count: number | null;
  readonly available_count: number | null;
}

export interface GameInfo {
  readonly game_id: string;
  readonly rounds_total: number;
  readonly round_number: number | null;
  readonly clip_seconds: number;
}

export interface GameRecord {
  readonly version: 2;
  readonly game_id: string;
  readonly finished_at: number;
  readonly players: readonly ViewPlayer[];
  readonly results: FinalResults;
  readonly teams: readonly TeamStanding[];
  readonly started_at: number | null;
  readonly settings: GameSettings | null;
  readonly sources: readonly ArchiveSource[];
}

export interface GameRules {
  readonly answer_max_chars: number;
  readonly scoring_mode: string;
  readonly acceptance_threshold: number;
  readonly answer_fields: readonly string[];
  readonly album_points: number;
  readonly year_points: number;
  readonly featuring_points: number;
  readonly custom_points: number;
  readonly answer_mode: string;
  readonly title_points: number;
  readonly artist_points: number;
  readonly instructions: string;
  readonly captured_policy: string;
}

export interface GameSettings {
  readonly scoring_mode: string;
  readonly acceptance_threshold: number;
  readonly answer_fields: readonly string[];
  readonly album_points: number;
  readonly year_points: number;
  readonly featuring_points: number;
  readonly auto_advance: boolean;
  readonly intermission_s: number;
  readonly custom_points: number;
  readonly rounds: number;
  readonly clip_seconds: number;
  readonly answer_grace_s: number;
  readonly sources: readonly SourceView[];
  readonly auto_start: boolean;
  readonly prefetch_depth: number;
  readonly allow_repeats: boolean;
  readonly answer_mode: string;
  readonly title_points: number;
  readonly artist_points: number;
  readonly instructions: string;
  readonly captured_policy: string;
  readonly normalize_audio: boolean;
  readonly avoid_silence: boolean;
  readonly balance_folders: boolean;
}

export interface HealthResponse {
  readonly status: "ok";
  readonly bridge: BridgeState | null;
}

export interface Hello {
  readonly t: "HELLO";
  readonly client_version: string;
  readonly protocol: number;
}

export interface HistoryEntry {
  readonly album_correct: boolean | null;
  readonly year_correct: boolean | null;
  readonly featuring_correct: boolean | null;
  readonly judgement: string;
  readonly title_correct: boolean | null;
  readonly artist_correct: boolean | null;
  readonly custom_correct: boolean | null;
  readonly round_id: string;
  readonly number: number;
  readonly text: string | null;
  readonly status: AnswerStatus;
  readonly elapsed_ms: number | null;
  readonly order: number | null;
  readonly near_tie: boolean;
  readonly points: number;
  readonly track: RevealTrack | null;
  readonly received_at_wall_ms: number | null;
  readonly included: boolean;
}

export interface HistoryItem {
  readonly game_id: string;
  readonly finished_at: number;
  readonly rounds_played: number;
  readonly participants: number;
}

export interface HistoryResponse {
  readonly version: 2;
  readonly items: readonly HistoryItem[];
  readonly retained_bytes: number;
  readonly max_games: number;
  readonly max_bytes: number;
  readonly retention_days: number;
  readonly durable: boolean;
}

export interface HostAddTime {
  readonly t: "HOST";
  readonly cmd: "add_time";
  readonly round_id: string;
  readonly args: AddTimeArgs;
}

export interface HostAdjust {
  readonly t: "HOST";
  readonly cmd: "adjust";
  readonly expected_phase: "IN_GAME";
  readonly args: AdjustArgs;
}

export interface HostClose {
  readonly t: "HOST";
  readonly cmd: "close";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface HostConfigure {
  readonly t: "HOST";
  readonly cmd: "configure";
  readonly expected_phase: "LOBBY" | "IN_GAME" | "FINAL_RESULTS";
  readonly args: SettingsPatch;
  readonly start_game?: boolean;
}

export interface HostElevateRequest {
  readonly host_password: string;
}

export interface HostElevateResponse {
  readonly role: "host";
  readonly host_mode: HostMode;
}

export interface HostEndGame {
  readonly t: "HOST";
  readonly cmd: "end_game";
  readonly round_id?: string | null;
  readonly expected_phase?: "LOBBY" | "IN_GAME" | "FINAL_SCORE_REVIEW" | "FINAL_RESULTS" | null;
  readonly args: EndGameArgs;
}

export interface HostEndSession {
  readonly t: "HOST";
  readonly cmd: "end_session";
  readonly expected_phase: "LOBBY" | "IN_GAME" | "FINAL_SCORE_REVIEW" | "FINAL_RESULTS";
  readonly args: EmptyArgs;
}

export interface HostFinalReset {
  readonly t: "HOST";
  readonly cmd: "final_reset";
  readonly expected_phase: "FINAL_SCORE_REVIEW";
  readonly args: EmptyArgs;
}

export interface HostFinalSet {
  readonly t: "HOST";
  readonly cmd: "final_set";
  readonly expected_phase: "FINAL_SCORE_REVIEW";
  readonly args: FinalSetArgs;
}

export interface HostFinalValidate {
  readonly t: "HOST";
  readonly cmd: "final_validate";
  readonly expected_phase: "FINAL_SCORE_REVIEW";
  readonly args: PublishArgs;
}

export interface HostFinaleReveal {
  readonly t: "HOST";
  readonly cmd: "finale_reveal";
  readonly expected_phase: "FINAL_SCORE_REVIEW";
  readonly args: FinaleRevealArgs;
}

export interface HostFinaleStop {
  readonly t: "HOST";
  readonly cmd: "finale_stop";
  readonly expected_phase: "FINAL_SCORE_REVIEW";
  readonly args: EmptyArgs;
}

export interface HostForceStart {
  readonly t: "HOST";
  readonly cmd: "force_start";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface HostJoinLock {
  readonly t: "HOST";
  readonly cmd: "join_lock";
  readonly expected_phase: "LOBBY" | "IN_GAME" | "FINAL_SCORE_REVIEW" | "FINAL_RESULTS";
  readonly args: JoinLockArgs;
}

export interface HostKick {
  readonly t: "HOST";
  readonly cmd: "kick";
  readonly expected_phase: "LOBBY" | "IN_GAME" | "FINAL_SCORE_REVIEW" | "FINAL_RESULTS";
  readonly args: PlayerArgs;
}

export interface HostMcView {
  readonly session: SessionInfo;
  readonly me: Me;
  readonly phase: GamePhase;
  readonly players: readonly ViewPlayer[];
  readonly standings: readonly StandingRow[];
  readonly game: GameInfo | null;
  readonly audio: AudioSlots;
  readonly play: PlayInfo | null;
  readonly final_results: FinalResults | null;
  readonly rules: GameRules | null;
  readonly paused: PauseInfo | null;
  readonly team_standings: readonly TeamStanding[];
  readonly finale: Finale | null;
  readonly kind: "host_mc";
  readonly round: RoundPending | RoundCountdown | RoundMcOpen | RoundPlayerReview | RoundRevealed | null;
  readonly host: HostPanel;
  readonly mc: McPanel;
}

export interface HostNewGame {
  readonly t: "HOST";
  readonly cmd: "new_game";
  readonly expected_phase: "FINAL_RESULTS";
  readonly args: NewGameArgs;
}

export interface HostNext {
  readonly t: "HOST";
  readonly cmd: "next";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface HostPanel {
  readonly auto_missing_references: number;
  readonly settings: GameSettings;
  readonly limits: ServerLimits;
  readonly commands: readonly string[];
  readonly start_blockers: readonly StartBlocker[];
  readonly bridge: BridgeStatus;
  readonly pool: PoolStatus | null;
  readonly players_ops: readonly PlayerOps[];
  readonly ready_check: ReadyCheck | null;
  readonly undo_round_id: string | null;
  readonly last_play_id: string | null;
  readonly final_review: readonly FinalReviewRow[] | null;
  readonly warnings: readonly HostWarning[];
  readonly history: readonly GameRecord[];
  readonly history_count: number;
  readonly bridges: readonly BridgeDetail[];
  readonly review_rounds: readonly ReviewRound[];
  readonly joins_locked: boolean;
}

export interface HostParticipation {
  readonly t: "HOST";
  readonly cmd: "participation";
  readonly expected_phase: "LOBBY";
  readonly args: ParticipationArgs;
}

export interface HostPause {
  readonly t: "HOST";
  readonly cmd: "pause";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface HostPlayerModeView {
  readonly session: SessionInfo;
  readonly me: Me;
  readonly phase: GamePhase;
  readonly players: readonly ViewPlayer[];
  readonly standings: readonly StandingRow[];
  readonly game: GameInfo | null;
  readonly audio: AudioSlots;
  readonly play: PlayInfo | null;
  readonly final_results: FinalResults | null;
  readonly rules: GameRules | null;
  readonly paused: PauseInfo | null;
  readonly team_standings: readonly TeamStanding[];
  readonly finale: Finale | null;
  readonly kind: "host_player";
  readonly round: RoundPending | RoundCountdown | RoundOpen | RoundPlayerReview | RoundRevealed | null;
  readonly host: HostPanel;
}

export interface HostPublish {
  readonly t: "HOST";
  readonly cmd: "publish";
  readonly round_id: string;
  readonly args: PublishArgs;
}

export interface HostRename {
  readonly t: "HOST";
  readonly cmd: "rename";
  readonly expected_phase: "LOBBY" | "IN_GAME" | "FINAL_SCORE_REVIEW" | "FINAL_RESULTS";
  readonly args: RenameArgs;
}

export interface HostReplay {
  readonly t: "HOST";
  readonly cmd: "replay";
  readonly round_id: string;
  readonly args: PlayIdArgs;
}

export interface HostResume {
  readonly t: "HOST";
  readonly cmd: "resume";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface HostScoreDraft {
  readonly t: "HOST";
  readonly cmd: "score_draft";
  readonly round_id: string;
  readonly args: ScoreDraftArgs;
}

export interface HostSelectTrack {
  readonly t: "HOST";
  readonly cmd: "select_track";
  readonly expected_phase: "LOBBY" | "IN_GAME";
  readonly args: SelectTrackArgs;
}

export interface HostSetMode {
  readonly t: "HOST";
  readonly cmd: "set_mode";
  readonly expected_phase: "LOBBY" | "IN_GAME" | "FINAL_SCORE_REVIEW" | "FINAL_RESULTS";
  readonly args: SetModeArgs;
}

export interface HostSkip {
  readonly t: "HOST";
  readonly cmd: "skip";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface HostStartGame {
  readonly t: "HOST";
  readonly cmd: "start_game";
  readonly expected_phase: "LOBBY";
  readonly args: EmptyArgs;
}

export interface HostStop {
  readonly t: "HOST";
  readonly cmd: "stop";
  readonly round_id: string;
  readonly args: PlayIdArgs;
}

export interface HostToFinalReview {
  readonly t: "HOST";
  readonly cmd: "to_final_review";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface HostTrackMetadata {
  readonly t: "HOST";
  readonly cmd: "track_metadata";
  readonly round_id: string;
  readonly args: TrackMetadataArgs;
}

export interface HostUndoPublish {
  readonly t: "HOST";
  readonly cmd: "undo_publish";
  readonly round_id: string;
  readonly args: EmptyArgs;
}

export interface JoinLockArgs {
  readonly locked: boolean;
}

export interface JoinRequest {
  readonly password: string;
  readonly nickname: string;
}

export interface JoinResponse {
  readonly player_id: string;
  readonly nickname: string;
  readonly role: Role;
}

export interface LibraryBridge {
  readonly bridge_id: string;
  readonly name: string;
  readonly online: boolean;
  readonly track_count: number;
  readonly root: FolderNode;
  readonly scanned_folders: readonly string[];
  readonly source_error: string | null;
}

export interface LibraryIssue {
  readonly bridge_id: string;
  readonly filename: string;
  readonly folder: string;
  readonly code: string;
}

export interface LibraryResponse {
  readonly bridges: readonly LibraryBridge[];
  readonly issues: readonly LibraryIssue[];
}

export interface LibrarySearch {
  readonly total: number;
  readonly tracks: readonly LibraryTrack[];
  readonly tags: readonly string[];
  readonly linked_to: readonly string[];
}

export interface LibraryTrack {
  readonly metadata_revision: number;
  readonly cleared_fields: readonly string[];
  readonly missing_references: readonly string[];
  readonly aliases: Readonly<Record<string, readonly string[]>> | null;
  readonly enabled: boolean;
  readonly tags: readonly string[];
  readonly linked_to: readonly string[];
  readonly consumption: string;
  readonly bridge_name: string;
  readonly duration_ms: number | null;
  readonly played: boolean;
  readonly reserved: boolean;
  readonly in_pool: boolean;
  readonly bridge_id: string;
  readonly track_id: string;
  readonly filename: string;
  readonly folder: string;
  readonly ext: string;
  readonly available: boolean;
  readonly title: string | null;
  readonly artist: string | null;
  readonly featuring: string | null;
  readonly album: string | null;
  readonly year: number | null;
}

export interface ManualTrackChoice {
  readonly round_number: number;
  readonly bridge_id: string | null;
  readonly track_id: string | null;
  readonly filename: string | null;
  readonly bridge_name: string | null;
  readonly folder: string | null;
  readonly title: string | null;
  readonly artist: string | null;
  readonly locked: boolean;
  readonly manual: boolean;
  readonly error: string | null;
}

export interface McOpenRow {
  readonly player_id: string;
  readonly validated: boolean;
  readonly text: string | null;
  readonly status: AnswerStatus;
}

export interface McPanel {
  readonly manual_choices: readonly ManualTrackChoice[];
  readonly selection_revision: number;
  readonly current_track: McTrackInfo | null;
  readonly upcoming: readonly McTrackInfo[];
}

export interface McTrackInfo {
  readonly bridge_name: string;
  readonly folder: string;
  readonly filename: string;
  readonly display_name: string | null;
  readonly asset_state: AssetState | null;
}

export interface Me {
  readonly player_id: string;
  readonly nickname: string;
  readonly role: Role;
  readonly host_mode: HostMode | null;
  readonly participant: boolean;
}

export interface MetadataEdit {
  readonly expected_revision?: number | null;
  readonly bridge_id: string;
  readonly track_id: string;
  readonly metadata: MusicalMetadata;
}

export interface MusicalMetadata {
  readonly cleared_fields?: readonly ("title" | "artist" | "album" | "featuring" | "year")[] | null;
  readonly aliases?: Readonly<Partial<Record<"title" | "artist" | "album" | "featuring", readonly string[]>>> | null;
  readonly title?: string | null;
  readonly artist?: string | null;
  readonly featuring?: string | null;
  readonly album?: string | null;
  readonly year?: number | null;
  readonly tags?: readonly string[] | null;
  readonly linked_to?: readonly string[] | null;
  readonly enabled?: boolean | null;
}

export interface MyAnswer {
  readonly status: AnswerStatus;
  readonly text: string | null;
  readonly draft_text: string | null;
}

export interface NewGameArgs {
  readonly reset_library?: boolean;
}

export interface OkResponse {
  readonly ok: true;
}

export interface ParticipationArgs {
  readonly player_id: string;
  readonly spectator?: boolean;
  readonly team?: string | null;
}

export interface PauseInfo {
  readonly paused_at: number;
  readonly remaining_ms: number;
  readonly clip_offset_s: number | null;
  readonly resume_at: number | null;
}

export interface Ping {
  readonly t: "PING";
  readonly c: number;
}

export interface PlayIdArgs {
  readonly play_id: string;
}

export interface PlayInfo {
  readonly play_id: string;
  readonly asset_id: string;
  readonly start_at: number;
  readonly clip_offset: number;
}

export interface PlayMsg {
  readonly t: "PLAY";
  readonly play_id: string;
  readonly asset_id: string;
  readonly start_at: number;
  readonly clip_offset: number;
}

export interface PlaybackReport {
  readonly t: "PLAYBACK_REPORT";
  readonly play_id: string;
  readonly late_ms: number;
  readonly offset: number;
  readonly rtt_min: number;
  readonly out_latency: number;
  readonly est_error_ms: number;
}

export interface PlayerArgs {
  readonly player_id: string;
}

export interface PlayerOps {
  readonly player_id: string;
  readonly connection: ConnectionState;
  readonly audio_state: AudioState;
  readonly audio_error: AudioErrorCode | null;
  readonly ready: boolean;
  readonly late_ms: number | null;
  readonly rtt_min_ms: number | null;
  readonly offset_ms: number | null;
}

export interface PlayerView {
  readonly session: SessionInfo;
  readonly me: Me;
  readonly phase: GamePhase;
  readonly players: readonly ViewPlayer[];
  readonly standings: readonly StandingRow[];
  readonly game: GameInfo | null;
  readonly audio: AudioSlots;
  readonly play: PlayInfo | null;
  readonly final_results: FinalResults | null;
  readonly rules: GameRules | null;
  readonly paused: PauseInfo | null;
  readonly team_standings: readonly TeamStanding[];
  readonly finale: Finale | null;
  readonly kind: "player";
  readonly round: RoundPending | RoundCountdown | RoundOpen | RoundPlayerReview | RoundRevealed | null;
}

export interface Pong {
  readonly t: "PONG";
  readonly c: number;
  readonly s: number;
}

export interface PoolStatus {
  readonly size: number;
  readonly remaining: number;
  readonly exhausted: boolean;
  readonly fresh: number;
  readonly played: number;
  readonly unavailable: number;
  readonly reserved: number;
}

export interface Progress {
  readonly validated: number;
  readonly expected: number;
}

export interface PublishArgs {
  readonly confirm_unreviewed?: boolean;
}

export interface ReadyCheck {
  readonly ready: number;
  readonly expected: number;
  readonly timeout_at: number;
  readonly can_force: boolean;
}

export interface RecoveryCode {
  readonly code: string;
}

export interface RecoveryRequest {
  readonly password: string;
  readonly code: string;
}

export interface RenameArgs {
  readonly player_id: string;
  readonly nickname: string;
}

export interface RevealRow {
  readonly player_id: string;
  readonly text: string | null;
  readonly status: AnswerStatus;
  readonly elapsed_ms: number | null;
  readonly order: number | null;
  readonly near_tie: boolean;
  readonly points: number;
}

export interface RevealTrack {
  readonly cleared_fields: readonly string[];
  readonly aliases: Readonly<Record<string, readonly string[]>> | null;
  readonly display_name: string;
  readonly folder: string;
  readonly title: string | null;
  readonly artist: string | null;
  readonly featuring: string | null;
  readonly album: string | null;
  readonly year: number | null;
}

export interface ReviewRound {
  readonly scoring_reference: MusicalMetadata | null;
  readonly reference_changed: boolean;
  readonly played: boolean;
  readonly full_review_allowed: boolean;
  readonly bridge_online: boolean;
  readonly round_id: string;
  readonly number: number;
  readonly track: RevealTrack | null;
  readonly answers: readonly ReviewRow[];
  readonly included: boolean;
  readonly state: string;
  readonly close_reason: string | null;
  readonly recovery_interrupted: boolean;
  readonly excerpt_duration_ms: number | null;
  readonly track_duration_ms: number | null;
  readonly metadata_revision: number;
}

export interface ReviewRow {
  readonly auto_evidence: readonly AutoMatchInfo[];
  readonly auto_overridden: boolean;
  readonly judgement: string;
  readonly title_correct: boolean | null;
  readonly artist_correct: boolean | null;
  readonly custom_correct: boolean | null;
  readonly album_correct: boolean | null;
  readonly year_correct: boolean | null;
  readonly featuring_correct: boolean | null;
  readonly score_revision: number;
  readonly player_id: string;
  readonly text: string | null;
  readonly status: AnswerStatus;
  readonly elapsed_ms: number | null;
  readonly order: number | null;
  readonly near_tie: boolean;
  readonly late_start_ms: number | null;
  readonly points_draft: number;
  readonly reviewed: boolean;
  readonly score_before: number;
  readonly received_at_wall_ms: number | null;
}

export interface RoundCountdown {
  readonly state: "COUNTDOWN";
  readonly round_id: string;
  readonly number: number;
  readonly official_start_at: number;
}

export interface RoundMcOpen {
  readonly state: "OPEN";
  readonly round_id: string;
  readonly number: number;
  readonly official_start_at: number;
  readonly deadline: number;
  readonly validated: number;
  readonly expected: number;
  readonly per_player: readonly McOpenRow[];
}

export interface RoundOpen {
  readonly state: "OPEN";
  readonly round_id: string;
  readonly number: number;
  readonly official_start_at: number;
  readonly deadline: number;
  readonly my_answer: MyAnswer;
  readonly progress: Progress | null;
}

export interface RoundPending {
  readonly state: "QUEUED" | "PREPARING" | "LOADING";
  readonly round_id: string;
  readonly number: number;
  readonly wait_reason: "pool_exhausted" | "bridge_offline" | null;
}

export interface RoundPlayerReview {
  readonly auto_advance_at: number | null;
  readonly state: "REVIEW";
  readonly round_id: string;
  readonly number: number;
  readonly my_answer: MyAnswer;
}

export interface RoundRevealed {
  readonly state: "REVEALED";
  readonly round_id: string;
  readonly number: number;
  readonly track: RevealTrack;
  readonly rows: readonly RevealRow[];
}

export interface ScoreDraftArgs {
  readonly player_id: string;
  readonly points: number;
  readonly judgement?: "manual" | "criteria";
  readonly title_correct?: boolean | null;
  readonly artist_correct?: boolean | null;
  readonly custom_correct?: boolean | null;
  readonly album_correct?: boolean | null;
  readonly year_correct?: boolean | null;
  readonly featuring_correct?: boolean | null;
  readonly expected_revision?: number | null;
}

export interface SelectTrackArgs {
  readonly round_number: number;
  readonly expected_revision: number;
  readonly bridge_id?: string | null;
  readonly track_id?: string | null;
}

export interface ServerLimits {
  readonly max_players: number;
  readonly clip_min_s: number;
  readonly clip_max_s: number;
  readonly answer_max_chars: number;
  readonly near_tie_ms: number;
  readonly ready_timeout_s: number;
  readonly clip_format: ClipFormat;
}

export interface SessionInfo {
  readonly epoch: string;
  readonly protocol: number;
  readonly server_version: string;
  readonly recovered: boolean;
  readonly persistence_status: string;
}

export interface SessionResponse {
  readonly player_id: string;
  readonly nickname: string;
  readonly role: Role;
  readonly host_mode: HostMode | null;
  readonly protocol: number;
  readonly server_version: string;
  readonly epoch: string;
}

export interface SetModeArgs {
  readonly mode: HostMode;
}

export interface SettingsPatch {
  readonly rounds?: number | null;
  readonly clip_seconds?: number | null;
  readonly answer_grace_s?: number | null;
  readonly sources?: readonly SourceSelection[] | null;
  readonly auto_start?: boolean | null;
  readonly auto_advance?: boolean | null;
  readonly intermission_s?: number | null;
  readonly custom_points?: number | null;
  readonly prefetch_depth?: number | null;
  readonly allow_repeats?: boolean | null;
  readonly answer_mode?: "title" | "artist" | "both" | "custom" | "fields" | null;
  readonly scoring_mode?: "manual" | "auto" | null;
  readonly acceptance_threshold?: number | null;
  readonly answer_fields?: readonly ("title" | "artist" | "album" | "year" | "featuring")[] | null;
  readonly album_points?: number | null;
  readonly year_points?: number | null;
  readonly featuring_points?: number | null;
  readonly title_points?: number | null;
  readonly artist_points?: number | null;
  readonly instructions?: string | null;
  readonly captured_policy?: "manual" | "zero" | null;
  readonly normalize_audio?: boolean | null;
  readonly avoid_silence?: boolean | null;
  readonly balance_folders?: boolean | null;
}

export interface SourceSelection {
  readonly bridge_id: string;
  readonly folder_prefix: string;
}

export interface SourceUpdate {
  readonly bridge_id: string;
  readonly folders?: readonly string[] | null;
}

export interface SourceView {
  readonly bridge_id: string;
  readonly folder_prefix: string;
}

export interface StandingRow {
  readonly player_id: string;
  readonly score: number;
  readonly rank: number;
}

export interface StateMsg {
  readonly t: "STATE";
  readonly v: number;
  readonly view: PlayerView | HostPlayerModeView | HostMcView;
}

export interface StopMsg {
  readonly t: "STOP";
  readonly play_id: string;
  readonly stop_at: number | null;
}

export interface TeamStanding {
  readonly team: string;
  readonly score: number;
  readonly rank: number;
  readonly members: readonly string[];
}

export interface TrackMetadataArgs {
  readonly cleared_fields?: readonly ("title" | "artist" | "album" | "featuring" | "year")[] | null;
  readonly aliases?: Readonly<Partial<Record<"title" | "artist" | "album" | "featuring", readonly string[]>>> | null;
  readonly title?: string | null;
  readonly artist?: string | null;
  readonly featuring?: string | null;
  readonly album?: string | null;
  readonly year?: number | null;
  readonly tags?: readonly string[] | null;
  readonly linked_to?: readonly string[] | null;
  readonly enabled?: boolean | null;
  readonly expected_revision?: number | null;
  readonly regrade_auto?: boolean;
}

export interface ViewPlayer {
  readonly id: string;
  readonly nickname: string;
  readonly online: boolean;
  readonly is_host: boolean;
  readonly is_me: boolean;
  readonly spectator: boolean;
  readonly team: string | null;
}

export type ClientMessage = Hello | Ping | AudioStatus | PlaybackReport | AnswerDraft | AnswerSubmit | HostSelectTrack | HostConfigure | HostSetMode | HostStartGame | HostNewGame | HostEndGame | HostEndSession | HostNext | HostForceStart | HostReplay | HostStop | HostPause | HostResume | HostSkip | HostAddTime | HostClose | HostScoreDraft | HostPublish | HostTrackMetadata | HostUndoPublish | HostAdjust | HostToFinalReview | HostFinalSet | HostFinalReset | HostFinalValidate | HostFinaleReveal | HostFinaleStop | HostKick | HostRename | HostParticipation | HostJoinLock;

export type HostCommand = HostSelectTrack | HostConfigure | HostSetMode | HostStartGame | HostNewGame | HostEndGame | HostEndSession | HostNext | HostForceStart | HostReplay | HostStop | HostPause | HostResume | HostSkip | HostAddTime | HostClose | HostScoreDraft | HostPublish | HostTrackMetadata | HostUndoPublish | HostAdjust | HostToFinalReview | HostFinalSet | HostFinalReset | HostFinalValidate | HostFinaleReveal | HostFinaleStop | HostKick | HostRename | HostParticipation | HostJoinLock;

export type ServerMessage = StateMsg | Pong | PlayMsg | StopMsg | AnswerAck | ErrorMsg;
