"""Generate ``web/src/protocol/generated.ts`` from the Pydantic protocol (spec §16).

Pydantic → JSON Schema → TypeScript, with an in-house converter of the small JSON Schema
subset Pydantic emits. Any unsupported structural keyword is an error, never a silent
``any``. The output is byte-for-byte deterministic.

Usage:
    uv run python tools/gen_ts_types.py                # write generated.ts
    uv run python tools/gen_ts_types.py --check        # fail on drift (generated.ts or lock)
    uv run python tools/gen_ts_types.py --update-lock  # rewrite protocol/schema.lock.json
"""

from __future__ import annotations

import argparse
import difflib
import enum
import json
import sys
from collections.abc import Iterable, Mapping
from pathlib import Path
from typing import Any

from openblindysir_protocol import enums as enum_module
from openblindysir_protocol import errors as error_module
from openblindysir_protocol.export import (
    EXPORTED_CONSTANTS,
    schema_fingerprints,
    web_json_schema,
)
from openblindysir_protocol.version import PROTOCOL_VERSION

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "web" / "src" / "protocol" / "generated.ts"
LOCK = ROOT / "protocol" / "schema.lock.json"
HEADER = "// AUTO-GENERATED by tools/gen_ts_types.py — DO NOT EDIT.\n"

# Keywords that only constrain or document values: ignored in TypeScript.
IGNORED_KEYS = frozenset(
    {
        "title",
        "default",
        "discriminator",
        "pattern",
        "minLength",
        "maxLength",
        "minimum",
        "maximum",
        "exclusiveMinimum",
        "exclusiveMaximum",
        "minItems",
        "maxItems",
        "format",
        "readOnly",
        "description",
    }
)
HANDLED_KEYS = frozenset(
    {"$ref", "const", "enum", "type", "anyOf", "oneOf", "items", "properties", "required"}
    | {"additionalProperties"}
)


class UnsupportedSchemaError(ValueError):
    """The schema uses a keyword outside the supported subset."""


def ref_name(ref: str) -> str:
    prefix = "#/$defs/"
    if not ref.startswith(prefix):
        raise UnsupportedSchemaError(f"unsupported $ref {ref!r}")
    return ref[len(prefix) :]


def literal(value: Any) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, str | int | float):
        return json.dumps(value, ensure_ascii=False)
    if value is None:
        return "null"
    raise UnsupportedSchemaError(f"unsupported literal {value!r}")


def check_keys(schema: Mapping[str, Any]) -> None:
    unknown = set(schema) - IGNORED_KEYS - HANDLED_KEYS
    if unknown:
        raise UnsupportedSchemaError(f"unsupported keyword(s) {sorted(unknown)}")


def type_expr(schema: Mapping[str, Any]) -> str:  # noqa: PLR0911, PLR0912 - one branch per keyword
    """TypeScript type expression of a JSON Schema fragment."""
    check_keys(schema)
    if "$ref" in schema:
        return ref_name(schema["$ref"])
    if "const" in schema:
        return literal(schema["const"])
    if "enum" in schema:
        return " | ".join(literal(value) for value in schema["enum"])
    for key in ("anyOf", "oneOf"):
        if key in schema:
            parts: list[str] = []
            for option in schema[key]:
                text = type_expr(option)
                if text not in parts:
                    parts.append(text)
            return " | ".join(parts)
    kind = schema.get("type")
    if kind == "string":
        return "string"
    if kind in {"integer", "number"}:
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item = type_expr(schema.get("items", {}))
        return f"readonly ({item})[]" if " " in item else f"readonly {item}[]"
    if kind == "object":
        if "properties" in schema:
            return inline_object(schema)
        extra = schema.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Readonly<Record<string, {type_expr(extra)}>>"
        if extra is None or extra is True:
            return "Readonly<Record<string, never>>"
    raise UnsupportedSchemaError(f"unsupported schema {dict(schema)!r}")


def property_lines(schema: Mapping[str, Any], indent: str) -> list[str]:
    required = set(schema.get("required", []))
    lines: list[str] = []
    for name, prop in schema.get("properties", {}).items():
        description = prop.get("description")
        if description:
            lines.append(f"{indent}/** {description} */")
        optional = "" if name in required else "?"
        lines.append(f"{indent}readonly {name}{optional}: {type_expr(prop)};")
    return lines


def inline_object(schema: Mapping[str, Any]) -> str:
    extra = schema.get("additionalProperties")
    if extra not in (None, False):
        raise UnsupportedSchemaError("objects mixing properties and additionalProperties")
    body = " ".join(line.strip() for line in property_lines(schema, ""))
    return "{ " + body + " }"


def interface(name: str, schema: Mapping[str, Any]) -> str:
    check_keys(schema)
    lines = [f"export interface {name} {{", *property_lines(schema, "  "), "}"]
    if not schema.get("properties"):
        lines = [f"export type {name} = Readonly<Record<string, never>>;"]
    return "\n".join(lines)


def string_enums() -> list[type[enum.StrEnum]]:
    found: dict[str, type[enum.StrEnum]] = {}
    for module in (enum_module, error_module):
        for value in vars(module).values():
            if (
                isinstance(value, type)
                and issubclass(value, enum.StrEnum)
                and value is not enum.StrEnum
            ):
                found[value.__name__] = value
    return [found[name] for name in sorted(found)]


def screaming_plural(name: str) -> str:
    snake = "".join(f"_{char}" if char.isupper() and i else char for i, char in enumerate(name))
    upper = snake.upper()
    return upper + ("ES" if upper.endswith(("S", "X", "SH", "CH")) else "S")


def enum_block(cls: type[enum.StrEnum]) -> str:
    values = [member.value for member in cls]
    union = " | ".join(literal(value) for value in values)
    array = ", ".join(literal(value) for value in values)
    return (
        f"export type {cls.__name__} = {union};\n"
        f"export const {screaming_plural(cls.__name__)} = [{array}] as const;"
    )


def generate(schema: Mapping[str, Any] | None = None) -> str:
    """Return the full content of ``generated.ts``."""
    schema = schema if schema is not None else web_json_schema()
    defs: Mapping[str, Any] = schema["$defs"]
    roots: Mapping[str, Any] = schema["roots"]
    enum_classes = string_enums()
    enum_names = {cls.__name__ for cls in enum_classes}

    blocks: list[str] = [HEADER.rstrip("\n")]
    for name, value in EXPORTED_CONSTANTS.items():
        blocks.append(f"export const {name} = {literal(value)};")
    blocks.append(
        "export const CloseCode = { "
        + ", ".join(f"{member.name}: {member.value}" for member in error_module.CloseCode)
        + " } as const;"
    )
    blocks.extend(enum_block(cls) for cls in enum_classes)

    for name in sorted(defs):
        definition = defs[name]
        if "enum" in definition:
            if name not in enum_names:
                raise UnsupportedSchemaError(f"enum {name} is not a protocol StrEnum")
            continue
        if definition.get("type") == "object" and "properties" in definition:
            blocks.append(interface(name, definition))
        else:
            blocks.append(f"export type {name} = {type_expr(definition)};")

    for name in sorted(roots):
        root = roots[name]
        if root.get("$ref") and ref_name(root["$ref"]) == name:
            continue
        blocks.append(f"export type {name} = {type_expr(root)};")
    return "\n\n".join(blocks) + "\n"


def read_lock() -> dict[str, Any]:
    return json.loads(LOCK.read_text(encoding="utf-8"))


def lock_content() -> str:
    data = {"protocol": PROTOCOL_VERSION, "roots": schema_fingerprints()}
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")


def unified(expected: str, actual: str, label: str) -> Iterable[str]:
    return difflib.unified_diff(
        actual.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=f"{label} (committed)",
        tofile=f"{label} (regenerated)",
    )


def check() -> int:
    status = 0
    expected = generate()
    actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
    if expected != actual:
        sys.stdout.writelines(unified(expected, actual, "generated.ts"))
        print("protocol drift: run `uv run python tools/gen_ts_types.py`", file=sys.stderr)
        status = 1
    if not LOCK.exists() or read_lock() != json.loads(lock_content()):
        print(
            "schema lock drift: bump PROTOCOL_VERSION if the schema changed, then run "
            "`uv run python tools/gen_ts_types.py --update-lock`",
            file=sys.stderr,
        )
        status = 1
    if status == 0:
        print("protocol types and schema lock are up to date")
    return status


def update_lock() -> int:
    if LOCK.exists():
        locked = read_lock()
        if locked["protocol"] == PROTOCOL_VERSION and locked["roots"] != schema_fingerprints():
            print(
                "refused: the schema changed but PROTOCOL_VERSION did not; bump it first",
                file=sys.stderr,
            )
            return 1
    write_text(LOCK, lock_content())
    print(f"wrote {LOCK.relative_to(ROOT).as_posix()}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=(__doc__ or "").splitlines()[0])
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--check", action="store_true", help="fail if outputs are outdated")
    group.add_argument("--update-lock", action="store_true", help="rewrite schema.lock.json")
    args = parser.parse_args(argv)
    if args.check:
        return check()
    if args.update_lock:
        return update_lock()
    write_text(OUTPUT, generate())
    print(f"wrote {OUTPUT.relative_to(ROOT).as_posix()}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
